# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PromiseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PromiseDemo
pod "PromiseKit/CorePromise", "~> 6.8"	

  target 'PromiseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PromiseDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
