# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 5.0'
  pod 'RxCocoa',    '~> 5.0'
  # Pods for RxSwiftDemo

  target 'RxSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
