# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'share' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
# U-Share SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’

  # 集成微信(精简版0.2M)
    pod ‘UMengUShare/Social/ReducedWeChat'
  
  # 集成QQ/QZone/TIM(精简版0.5M)
    pod ‘UMengUShare/Social/ReducedQQ'
# 集成新浪微博(精简版1M)
    pod ‘UMengUShare/Social/ReducedSina'

  # Pods for share

  target 'shareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
